#!/usr/bin/env bash
#A script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.

a=0

while [ $a -le 10 ]
do
	if [ $a -eq 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi

	((a++))
done
